INSERT OR IGNORE INTO content_items (title, slug, pillar, summary, publish_date, status, created_at) VALUES
('Longevity Infrastructure 101: Why Biology Beats Lifestyle Optics', 'longevity-infrastructure-101', 'longevity-wellness', 'A field-grounded framework for evaluating health outcomes through air, water, food, and soil quality over decades.', '2026-03-01', 'published', datetime('now')),
('How To Verify Organic Claims Without Falling For Labels', 'verify-organic-claims', 'organic-clean-food', 'A practical verification method using certification evidence, farm visits, and recurring lab testing.', '2026-03-02', 'published', datetime('now')),
('People Behind The Land: Why On-Ground Operators Matter', 'people-behind-the-land', 'people-behind-land', 'Operator continuity and local farm knowledge as the hidden variable in long-term farm outcomes.', '2026-03-03', 'published', datetime('now')),
('Community As Infrastructure: Shared Meals, Shared Accountability', 'community-as-infrastructure', 'community-experiences', 'How curated community design reduces drift and increases stewardship quality in habitat projects.', '2026-03-03', 'published', datetime('now')),
('Sustainability That Pays: Operating Economics Without Maintenance Traps', 'sustainability-that-pays', 'sustainability-pays', 'A model for sustaining operations from farm activity rather than fee extraction from owners.', '2026-03-04', 'published', datetime('now')),
('Transparency Systems: Turning Trust Into A Repeatable Process', 'transparency-systems', 'transparency-trust', 'How testing cadence, origin disclosure, and open visits create durable trust signals.', '2026-03-04', 'published', datetime('now')),
('Guide: Pre-Site-Visit Checklist For Families', 'pre-site-visit-checklist', 'transparency-trust', 'Questions to prepare before a farm visit so you can evaluate facts and avoid sales theater.', '2026-03-05', 'published', datetime('now')),
('Guide: Mapping Seasonal Produce To Household Needs', 'seasonal-produce-household-planning', 'organic-clean-food', 'A practical planning guide for matching seasonal availability with real household consumption.', '2026-03-06', 'published', datetime('now')),
('Guide: Evaluating Farm Habitat Governance Before You Buy', 'farm-habitat-governance-guide', 'community-experiences', 'Governance patterns that keep communities stable and prevent long-term model drift.', '2026-03-07', 'published', datetime('now')),
('Managed Farmland Due Diligence Checklist', 'managed-farmland-due-diligence-checklist', 'transparency-trust', 'The full checklist used to evaluate legal, operational, organic, and economic integrity before committing capital.', '2026-03-08', 'published', datetime('now'));
